// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SalesTaxLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("zip")]
        public long Zip { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("rate")]
        public double Rate { get; set; }

        [JsonProperty("county")]
        public double County { get; set; }

        [JsonProperty("city")]
        public double City { get; set; }

        [JsonProperty("special")]
        public double Special { get; set; }
    }
}
